name: Tests and checks
on: pull_request
jobs:
  test:
    name: App tests and checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Compile artifacts
        run: npm run compile
      - name: Run checks
        run: npm run check
      - name: Run tests
        run: npm run test
